# Generated by Django 5.1.15 on 2026-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
