# Generated by Django 5.1.15 on 2026-08-28 19:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pg_textsearch'),
        ('merchants', '0008_merchant_shipping_price_merchant_shipping_service_and_more'),
        ('offers', '0003_discoveredoffer_observed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(db_index=True, help_text='e.g. prom_a1b2c3d4e5f6', max_length=120, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 10.00 for 10% off', max_digits=5, null=True)),
                ('price_off', models.DecimalField(blank=True, decimal_places=2, help_text='Flat ZAR discount amount', max_digits=12, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='merchants.merchant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
