# Generated by Django 5.1.15 on 2026-08-28 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pg_textsearch'),
        ('offers', '0004_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('contact', models.CharField(help_text='WhatsApp number or email address', max_length=255)),
                ('threshold_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
