# Generated by Django 5.1.15 on 2026-08-29 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_masterproduct_master_category_categorypath'),
        ('merchants', '0011_follow'),
        ('offers', '0005_pricealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(blank=True, db_index=True, help_text='e.g. vp_ab12cd34ef56', max_length=120, unique=True)),
                ('vendor_sku', models.CharField(blank=True, db_index=True, default='', help_text="The merchant's own SKU for this listing", max_length=100)),
                ('vendor_gtin', models.CharField(blank=True, help_text='Vendor barcode when it differs from the master GTIN', max_length=14, null=True)),
                ('mpn', models.CharField(blank=True, default='', max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used'), ('open_box', 'Open Box')], default='new', max_length=20)),
                ('unit_descriptor', models.CharField(blank=True, default='', help_text='e.g. each, per 5L, box of 10', max_length=50)),
                ('stock_state', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('stall_ref', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('offboarded', 'Offboarded / Suspended')], db_index=True, default='active', max_length=20)),
                ('match_source', models.CharField(choices=[('sweep', 'Public Web Sweep'), ('manual', 'Operator Entered'), ('merchant_claimed', 'Merchant Claimed'), ('evidence', 'Field Evidence')], default='manual', max_length=30)),
                ('match_confidence', models.FloatField(default=0.85)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='catalog.masterproduct')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Vendor Product Listing',
                'verbose_name_plural': 'Vendor Product Listings',
                'ordering': ['merchant', 'master_product'],
            },
        ),
        migrations.AddField(
            model_name='discoveredoffer',
            name='vendor_product',
            field=models.ForeignKey(blank=True, help_text='Listing this sweep resolved to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_offers', to='offers.vendorproduct'),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor_product',
            field=models.ForeignKey(blank=True, help_text='Stable listing this price-state record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.vendorproduct'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='vendor_product',
            field=models.ForeignKey(blank=True, help_text='Listing this promotion applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='offers.vendorproduct'),
        ),
        migrations.AddConstraint(
            model_name='vendorproduct',
            constraint=models.UniqueConstraint(fields=('merchant', 'master_product', 'condition', 'unit_descriptor'), name='uniq_vendor_product_listing'),
        ),
    ]
