# Generated by Django 5.1.15 on 2026-08-29 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_masterproduct_master_category_categorypath'),
        ('merchants', '0012_alter_draft_draft_type'),
        ('offers', '0007_backfill_vendor_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('trigger', models.CharField(choices=[('periodic', 'Periodic Rotation'), ('impression', 'Impression-Driven'), ('manual', 'Manual / Dashboard'), ('discovery', 'Discovery Pass')], default='periodic', max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('urls_attempted', models.PositiveIntegerField(default=0)),
                ('urls_ok', models.PositiveIntegerField(default=0)),
                ('urls_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_runs', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Crawl Run',
                'verbose_name_plural': 'Crawl Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(blank=True, db_index=True, max_length=120, unique=True)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('final_url', models.URLField(blank=True, default='', help_text='URL after redirect resolution')),
                ('expected_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('last_image_url', models.URLField(blank=True, default='')),
                ('state', models.CharField(choices=[('unknown', 'Never Checked'), ('healthy', 'Healthy'), ('failed', 'Check Failed'), ('off_domain', 'Resolves Off Domain')], db_index=True, default='unknown', max_length=20)),
                ('checks_count', models.PositiveIntegerField(default=0)),
                ('last_crawled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_title', models.CharField(blank=True, default='', max_length=300)),
                ('last_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_drift_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_availability_text', models.CharField(blank=True, default='', max_length=100)),
                ('error_text', models.TextField(blank=True, default='')),
                ('refresh_requested_at', models.DateTimeField(blank=True, db_index=True, help_text='Set by impressions; drained by the next crawl', null=True)),
                ('refresh_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(db_index=True, default='web_sweep', max_length=30)),
                ('discovered_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_health_records', to='offers.discoveredoffer')),
                ('master_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_health_records', to='catalog.masterproduct')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_health_records', to='merchants.merchant')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_health_records', to='offers.offer')),
            ],
            options={
                'verbose_name': 'URL Health Record',
                'verbose_name_plural': 'URL Health Records',
                'ordering': ['-last_crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('source', models.CharField(default='search', max_length=30)),
                ('seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_impressions', to='merchants.merchant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_impressions', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'URL Impression',
                'verbose_name_plural': 'URL Impressions',
                'ordering': ['-seen_at'],
            },
        ),
    ]
