# Generated by Django 5.1.15 on 2026-08-25 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(db_index=True, help_text='Unique canonical ID (e.g. m_01, mkt_01_s01)', max_length=120, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Public operating trading name', max_length=255)),
                ('country', models.CharField(choices=[('ZA', 'South Africa (ZA)'), ('ZW', 'Zimbabwe (ZW)'), ('KE', 'Kenya (KE)'), ('NG', 'Nigeria (NG)'), ('GB', 'United Kingdom (GB)'), ('US', 'United States (US)')], db_index=True, default='ZA', max_length=2)),
                ('claim_state', models.CharField(choices=[('candidate', 'Candidate Profile (Preloaded)'), ('claimed', 'Claimed by Merchant'), ('disputed', 'Disputed Ownership'), ('offboarded', 'Offboarded / Suspended')], db_index=True, default='candidate', max_length=30)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified'), ('phone_verified', 'Phone Verified (OTP)'), ('fully_verified', 'Fully Verified (Field/Document)')], db_index=True, default='unverified', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp format e.g. 27712345678', max_length=40, null=True)),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('stall_identifier', models.CharField(blank=True, help_text='e.g. "Building 2, Shop B-18" or "Stall 44"', max_length=150, null=True)),
                ('category', models.CharField(blank=True, db_index=True, help_text='solar_energy, smartphones, hardware, groceries, etc.', max_length=100, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('google_reviews_count', models.IntegerField(default=0)),
                ('google_reviews_url', models.URLField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('cipc_enterprise_number', models.CharField(blank=True, help_text='CIPC e.g. K2021/123456/07', max_length=100, null=True)),
                ('csd_supplier_number', models.CharField(blank=True, help_text='National Treasury CSD MAAA...', max_length=100, null=True)),
                ('cidb_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cidb_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('wireman_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bbbee_level', models.CharField(blank=True, max_length=150, null=True)),
                ('tax_compliance_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('storefront_photo_url', models.URLField(blank=True, null=True)),
                ('years_in_business', models.IntegerField(default=1)),
                ('median_response_minutes', models.IntegerField(default=15)),
                ('delivery_options', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('trust_score', models.IntegerField(default=80, help_text='0 to 100 calculated trust metric')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='markets.market')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['-trust_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrustPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=85)),
                ('fresh_offers_today_count', models.IntegerField(default=0)),
                ('median_response_minutes', models.IntegerField(default=10)),
                ('complaint_count_last_90d', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('VERIFIED_ACTIVE', 'Verified Active'), ('FLAGGED', 'Flagged for Review'), ('SUSPENDED', 'Suspended')], default='VERIFIED_ACTIVE', max_length=30)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_passport', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
