# Generated by Django 6.1 on 2026-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_merchant_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='operating_hours_json',
            field=models.JSONField(blank=True, default=dict, help_text='Per-weekday [open, close] pairs; null/omitted = closed'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='reviews_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Rating distribution, avg, count'),
        ),
    ]
