# Generated by Django 5.1.15 on 2026-08-26 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_merchant_trust_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who manages this merchant record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_merchants', to=settings.AUTH_USER_MODEL),
        ),
    ]
