# Generated by Django 6.1 on 2026-08-27 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchant_operating_hours_json_and_more'),
        ('offers', '0002_alter_offer_price_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCentreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT % e.g. 15.00', max_digits=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centre_settings', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Centre Settings',
                'verbose_name_plural': 'Merchant Centre Settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, help_text='Human-friendly order ref e.g. ORD-2026-0001', max_length=120, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_contact', models.CharField(blank=True, help_text='WhatsApp / phone', max_length=80, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=30)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_method', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Order',
                'verbose_name_plural': 'Merchant Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='offers.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchants.order')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('promo_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping'), ('bundle', 'Bundle / Buy X Get Y')], default='percentage', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Percent (0-100) or fixed ZAR amount', max_digits=12)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Optional coupon code', max_length=60, null=True)),
                ('scope', models.CharField(choices=[('storewide', 'Storewide'), ('category', 'Specific Category'), ('offer', 'Specific Product / Offer')], default='storewide', max_length=30)),
                ('target_ref', models.CharField(blank=True, help_text='Category slug or offer canonical_id when scoped', max_length=160, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Promotion',
                'verbose_name_plural': 'Merchant Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(help_text='e.g. Standard Courier, Collection, Same-Day', max_length=120)),
                ('zone', models.CharField(blank=True, help_text="Region/city or 'national'", max_length=120, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping threshold', max_digits=12, null=True)),
                ('eta_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery days')),
                ('active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['rate'],
            },
        ),
    ]
