# Generated by Django 5.1.15 on 2026-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_alter_merchant_options_alter_merchant_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard shipping price in ZAR (feed g:shipping)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='shipping_service',
            field=models.CharField(blank=True, default='', help_text='Shipping service name, e.g. Standard Courier', max_length=80),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate percentage, e.g. 15.00 (feed g:tax)', max_digits=5, null=True),
        ),
    ]
