# Generated by Django 5.1.15 on 2026-08-28 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_merchant_shipping_price_merchant_shipping_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='special_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"2026-12-25": {"closed": true}, "2026-12-26": {"open": "09:00", "close": "13:00"}}', null=True),
        ),
        migrations.CreateModel(
            name='MerchantPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved')], db_index=True, default='pending', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Photo',
                'verbose_name_plural': 'Merchant Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('text', 'Update'), ('offer', 'Offer')], default='text', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Post',
                'verbose_name_plural': 'Merchant Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asker_name', models.CharField(max_length=120)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved')], db_index=True, default='pending', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Question',
                'verbose_name_plural': 'Merchant Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('comment', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reply_text', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Review',
                'verbose_name_plural': 'Merchant Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
