# Generated by Django 5.1.15 on 2026-08-28 20:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0009_merchant_special_hours_merchantphoto_merchantpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(db_index=True, help_text='e.g. cmp_abc123', max_length=120, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(choices=[('hyperlocal', 'Hyperlocal Radius'), ('shopping_offer', 'Shopping Offer'), ('brand', 'Brand Awareness')], db_index=True, default='hyperlocal', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=20)),
                ('budget_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Optional budget cap in ZAR', max_digits=12, null=True)),
                ('target_province', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('radius_km', models.IntegerField(blank=True, help_text='Optional radius targeting', null=True)),
                ('target_category', models.CharField(blank=True, default='', max_length=100)),
                ('headline', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
