# Generated by Django 5.1.15 on 2026-08-28 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower_key', models.CharField(db_index=True, max_length=128)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Follow',
                'verbose_name_plural': 'Merchant Follows',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'follower_key'), name='unique_merchant_follower')],
            },
        ),
    ]
