# Generated by Django 5.1.15 on 2026-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralevent',
            name='action',
            field=models.CharField(choices=[('whatsapp_start', 'WhatsApp Chat Initiated'), ('outbound_click', 'Outbound Link Click'), ('call_reveal', 'Phone Number Reveal'), ('directions_open', 'Google Maps Directions Opened'), ('quote_submitted', 'Commercial RFQ Submitted'), ('reserve_intent', 'Stock Reservation Intent'), ('comparison_view', 'Multi-Seller Matrix View'), ('search_result_view', 'Search Result View'), ('answer_view', 'AI Answer View'), ('short_view', 'Short Video View'), ('show_view', 'Show Episode View'), ('merchant_profile_view', 'Merchant Profile View'), ('destination_ack', 'Destination Acknowledged'), ('purchase_confirmed_external', 'Purchase Confirmed at External Destination')], db_index=True, default='whatsapp_start', max_length=50),
        ),
    ]
