# Generated by Django 5.1.15 on 2026-08-25 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('canonical_slug', models.SlugField(max_length=255, unique=True)),
                ('market_type', models.CharField(choices=[('formal_mega_mall', 'Formal Mega-Mall'), ('shopping_centre', 'Shopping Centre'), ('strip_mall', 'Strip Mall / Retail Park'), ('wholesale_market', 'Wholesale / B2B Trade Market'), ('informal_transport_rank', 'Informal Transport / Taxi Rank Hub'), ('township_commercial_cluster', 'Township Commercial Cluster'), ('flea_market', 'Flea / Street Market'), ('street_corridor', 'Commercial Street Corridor'), ('virtual_marketplace', 'Virtual Marketplace'), ('virtual_b2b_network', 'Virtual B2B Network')], db_index=True, default='shopping_centre', max_length=50)),
                ('country', models.CharField(db_index=True, default='ZA', max_length=2)),
                ('province', models.CharField(db_index=True, help_text='e.g. Gauteng, Western Cape, KwaZulu-Natal', max_length=100)),
                ('metro', models.CharField(db_index=True, help_text='e.g. City of Johannesburg, City of Cape Town, eThekwini', max_length=100)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified Discovery Scaffolding'), ('claimed', 'Claimed by Operator'), ('evidence_verified', 'Field / Cadastral Verified')], db_index=True, default='unverified', max_length=30)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stall_capacity', models.IntegerField(default=50)),
                ('active_merchants_count', models.IntegerField(default=0)),
                ('operating_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('landmarks', models.JSONField(blank=True, default=list, help_text='List of prominent nearby landmarks')),
                ('safety_notices', models.JSONField(blank=True, default=list, help_text='Security and visitor guidelines')),
                ('parent_market', models.ForeignKey(blank=True, help_text='Enclosing parent market (Strict Markets-in-Markets containment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_markets', to='markets.market')),
            ],
            options={
                'verbose_name': 'Market / Shopping Centre',
                'verbose_name_plural': 'Markets & Shopping Centres',
                'ordering': ['province', 'name'],
            },
        ),
    ]
