# Generated by Django 5.1.15 on 2026-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image_url',
            field=models.URLField(blank=True, help_text='Hero/exteriors image used for structured data and social cards', null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='locality',
            field=models.CharField(blank=True, db_index=True, help_text='Town or suburb, e.g. Sandton', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='market',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='market',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"mon": {"open": "09:00", "close": "18:00"}, ...}'),
        ),
        migrations.AddField(
            model_name='market',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA zone, e.g. Africa/Johannesburg', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='Human-readable hours summary', max_length=255, null=True),
        ),
    ]
