import { Market, ProductVariant, Offer, CommercialLocation, TrustPassport, Merchant } from '@shoppage/contracts';
import { enrichProductVariant } from '../enrichment/enricher';

/**
 * South African Flagship Seed Dataset (v7.0)
 * Markets, Canonical Products, Merchants & Live Offers
 */

export const SA_FLAGSHIP_MARKETS: Market[] = [
  {
    id: 'mkt_sandton_city',
    name: 'Sandton City & Nelson Mandela Square',
    canonicalSlug: 'sandton-city-johannesburg',
    marketType: 'formal_mega_mall',
    country: 'ZA',
    province: 'Gauteng',
    metro: 'City of Johannesburg',
    landmarks: ['Gautrain Sandton Station', 'Nelson Mandela Square Statue', 'Sandton Convention Centre'],
    safetyNotices: ['Secure covered parking', '24/7 security control room'],
  },
  {
    id: 'mkt_mall_of_africa',
    name: 'Mall of Africa (Waterfall City)',
    canonicalSlug: 'mall-of-africa-midrand',
    marketType: 'formal_mega_mall',
    country: 'ZA',
    province: 'Gauteng',
    metro: 'City of Johannesburg',
    landmarks: ['Waterfall City Park', 'Allandale Interchange'],
  },
  {
    id: 'mkt_dragon_city',
    name: 'Dragon City Wholesale Mall',
    canonicalSlug: 'dragon-city-crown-mines',
    marketType: 'wholesale_market',
    country: 'ZA',
    province: 'Gauteng',
    metro: 'City of Johannesburg',
    landmarks: ['Crown Mines Commercial Precinct', 'Main Reef Road'],
    safetyNotices: ['Cashless payments preferred', 'Wholesale minimum quantities apply at select stalls'],
  },
  {
    id: 'mkt_oriental_plaza',
    name: 'Oriental Plaza Fordsburg',
    canonicalSlug: 'oriental-plaza-fordsburg',
    marketType: 'wholesale_market',
    country: 'ZA',
    province: 'Gauteng',
    metro: 'City of Johannesburg',
    landmarks: ['Bree Street West', 'Lilian Ngoyi St'],
  },
  {
    id: 'mkt_soweto_bara',
    name: 'Chris Hani Baragwanath Transport & Commercial Hub',
    canonicalSlug: 'bara-taxi-rank-soweto',
    marketType: 'informal_transport_rank',
    country: 'ZA',
    province: 'Gauteng',
    metro: 'City of Johannesburg',
    landmarks: ['Chris Hani Baragwanath Hospital', 'Bara Taxi Rank Deck', 'Old Potch Road'],
    safetyNotices: ['Peak congestion 06:30-08:30 and 16:30-18:30'],
  },
  {
    id: 'mkt_gateway_durban',
    name: 'Gateway Theatre of Shopping (Umhlanga)',
    canonicalSlug: 'gateway-theatre-of-shopping-durban',
    marketType: 'formal_mega_mall',
    country: 'ZA',
    province: 'KwaZulu-Natal',
    metro: 'eThekwini',
    landmarks: ['Palm Boulevard', 'Wavehouse'],
  },
  {
    id: 'mkt_va_waterfront',
    name: 'V&A Waterfront',
    canonicalSlug: 'va-waterfront-cape-town',
    marketType: 'formal_mega_mall',
    country: 'ZA',
    province: 'Western Cape',
    metro: 'City of Cape Town',
    landmarks: ['Cape Town Harbour', 'Zeitz MOCAA'],
  },
];

const RAW_CANONICAL_PRODUCTS: ProductVariant[] = [
  {
    canonicalId: 'var_deye_5kw_hybrid',
    familyRef: 'fam_deye_inverters',
    categoryRef: 'solar_energy',
    title: 'Deye 5kW 48V Single Phase Hybrid Inverter (SUN-5K-SG03LP1-EU)',
    brand: 'Deye',
    modelNumber: 'SUN-5K-SG03LP1-EU',
    identifiers: {
      gtin13: '6971234567895',
      mpn: 'SUN-5K-SG03LP1-EU',
    },
    attributes: {
      ratedPowerKw: 5.0,
      dcBusVoltage: 48,
      maxPvInputVoltage: 500,
      mpptVoltageRange: '125-425V',
      ipRating: 'IP65',
      warrantyYears: 5,
    },
    aliases: [
      { phrase: 'Deye 5kVA inverter', locale: 'en', source: 'merchant_usage', confidence: 0.95 },
      { phrase: 'Deye omsetter 5kw', locale: 'af', source: 'merchant_usage', confidence: 0.9 },
      { phrase: 'Deye 5000W backup', locale: 'en', source: 'search_query', confidence: 0.85 },
    ],
    compatibilityEdgeCount: 14,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG'],
    provenance: {
      sourceRef: 'src_manufacturer_deye',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_sunsynk_8kw_hybrid',
    familyRef: 'fam_sunsynk_inverters',
    categoryRef: 'solar_energy',
    title: 'Sunsynk 8kW 48V Single Phase Hybrid Inverter',
    brand: 'Sunsynk',
    modelNumber: 'SUN-8K-SG01LP1',
    identifiers: {
      gtin13: '6009876543217',
      mpn: 'SUN-8K-SG01LP1',
    },
    attributes: {
      ratedPowerKw: 8.0,
      dcBusVoltage: 48,
      maxPvInputVoltage: 500,
      ipRating: 'IP65',
      warrantyYears: 5,
    },
    aliases: [
      { phrase: 'Sunsynk 8kVA inverter', locale: 'en', source: 'merchant_usage', confidence: 0.95 },
      { phrase: 'amapaneli sunsynk 8kw', locale: 'zu', source: 'search_query', confidence: 0.88 },
    ],
    compatibilityEdgeCount: 18,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE'],
    provenance: {
      sourceRef: 'src_manufacturer_sunsynk',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_dyness_5kwh_battery',
    familyRef: 'fam_dyness_batteries',
    categoryRef: 'solar_energy',
    title: 'Dyness BX51100 5.12kWh 48V Lithium-ion Battery',
    brand: 'Dyness',
    modelNumber: 'BX51100',
    identifiers: {
      gtin13: '6979876543210',
      mpn: 'BX51100',
    },
    attributes: {
      nominalCapacityKwh: 5.12,
      nominalVoltage: 51.2,
      maxDischargeCurrentA: 100,
      cycleLife: 6000,
      warrantyYears: 10,
    },
    aliases: [
      { phrase: 'Dyness 5.12kwh battery', locale: 'en', source: 'merchant_usage', confidence: 0.98 },
      { phrase: 'Dyness lithium 48v', locale: 'en', source: 'search_query', confidence: 0.9 },
    ],
    compatibilityEdgeCount: 12,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG'],
    provenance: {
      sourceRef: 'src_manufacturer_dyness',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_samsung_a16_128gb',
    familyRef: 'fam_samsung_a_series',
    categoryRef: 'smartphones',
    title: 'Samsung Galaxy A16 128GB LTE Dual SIM (Black)',
    brand: 'Samsung',
    modelNumber: 'SM-A165F',
    identifiers: {
      gtin13: '8806091876543',
      mpn: 'SM-A165F-BLK',
    },
    attributes: {
      storageGb: 128,
      ramGb: 4,
      displaySizeInches: 6.7,
      batteryMah: 5000,
      network: '4G LTE',
    },
    aliases: [
      { phrase: 'Samsung A16 128GB', locale: 'en', source: 'merchant_usage', confidence: 0.98 },
      { phrase: 'Galaxy A16 phone', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 6,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG', 'GB'],
    provenance: {
      sourceRef: 'src_manufacturer_samsung',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_tesla_cybertruck_ref',
    familyRef: 'fam_tesla_cybertruck',
    categoryRef: 'automotive',
    title: 'Tesla Cybertruck Foundation Series Tri-Motor AWD',
    brand: 'Tesla',
    modelNumber: 'CYBERTRUCK-TRI',
    identifiers: {
      mpn: 'CYBER-TRI-2026',
    },
    attributes: {
      acceleration0to100: '2.6s',
      towingCapacityKg: 4990,
      rangeKm: 515,
    },
    aliases: [
      { phrase: 'Cybertruck South Africa', locale: 'en', source: 'search_query', confidence: 0.9 },
    ],
    compatibilityEdgeCount: 0,
    status: 'reference_only', // REFERENCE ONLY - No local availability in ZA
    countryScope: ['US'],
    provenance: {
      sourceRef: 'src_tesla_us',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.95,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_ja_solar_550w',
    familyRef: 'fam_ja_solar_panels',
    categoryRef: 'solar_energy',
    title: 'JA Solar 550W Mono MBB Percium Solar Panel (JAM72S30-550/MR)',
    brand: 'JA Solar',
    modelNumber: 'JAM72S30-550/MR',
    identifiers: {
      gtin13: '6972345678901',
      mpn: 'JAM72S30-550/MR',
    },
    attributes: {
      ratedPowerWatts: 550,
      efficiencyPercent: 21.3,
      cellType: 'Monocrystalline Perc',
      warrantyYears: 12,
      estimatedPriceZar: 1850,
    },
    aliases: [
      { phrase: 'JA Solar 550W panel', locale: 'en', source: 'search_query', confidence: 0.98 },
      { phrase: '550w solar panel', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 20,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG'],
    provenance: {
      sourceRef: 'src_manufacturer_jasolar',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_freedom_won_10kwh',
    familyRef: 'fam_freedom_won_batteries',
    categoryRef: 'solar_energy',
    title: 'Freedom Won LiTE Home 10/8 10kWh 52V LiFePO4 Lithium Battery',
    brand: 'Freedom Won',
    modelNumber: 'FW-LITE-HOME-10-8',
    identifiers: {
      gtin13: '6001234567890',
      mpn: 'LITE-HOME-10/8',
    },
    attributes: {
      nominalCapacityKwh: 10.0,
      usableCapacityKwh: 8.0,
      nominalVoltage: 52.0,
      maxDischargeCurrentA: 200,
      cycleLife: 8000,
      warrantyYears: 10,
      estimatedPriceZar: 46900,
    },
    aliases: [
      { phrase: 'Freedom Won 10kWh battery', locale: 'en', source: 'search_query', confidence: 0.98 },
      { phrase: '10kwh lithium battery', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 16,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE'],
    provenance: {
      sourceRef: 'src_manufacturer_freedomwon',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_ppc_surebuild_50kg',
    familyRef: 'fam_ppc_cement',
    categoryRef: 'hardware',
    title: 'PPC Surebuild 42.5N General Purpose Cement 50kg',
    brand: 'PPC',
    modelNumber: 'PPC-SUREBUILD-50KG',
    identifiers: {
      gtin13: '6001087000014',
      mpn: 'PPC-SB-50KG',
    },
    attributes: {
      weightKg: 50,
      strengthClass: '42.5N',
      sabsApproved: true,
      estimatedPriceZar: 115,
    },
    aliases: [
      { phrase: 'PPC cement 50kg', locale: 'en', source: 'search_query', confidence: 0.99 },
      { phrase: 'Surebuild cement 50kg', locale: 'en', source: 'search_query', confidence: 0.98 },
      { phrase: '50kg cement', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 8,
    status: 'active',
    countryScope: ['ZA', 'ZW'],
    provenance: {
      sourceRef: 'src_manufacturer_ppc',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_samsung_s24_ultra_256gb',
    familyRef: 'fam_samsung_s_series',
    categoryRef: 'smartphones',
    title: 'Samsung Galaxy S24 Ultra 256GB 5G (Titanium Black)',
    brand: 'Samsung',
    modelNumber: 'SM-S928B',
    identifiers: {
      gtin13: '8806095387458',
      mpn: 'SM-S928BZKGEUB',
    },
    attributes: {
      storageGb: 256,
      ramGb: 12,
      displaySizeInches: 6.8,
      cameraMp: '200MP + 50MP + 12MP + 10MP',
      batteryMah: 5000,
      network: '5G',
      estimatedPriceZar: 23999,
    },
    aliases: [
      { phrase: 'Samsung S24 Ultra', locale: 'en', source: 'search_query', confidence: 0.99 },
      { phrase: 'Galaxy S24 Ultra phone', locale: 'en', source: 'search_query', confidence: 0.98 },
      { phrase: 's24 ultra 256gb', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 10,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG', 'GB', 'US'],
    provenance: {
      sourceRef: 'src_manufacturer_samsung',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_apple_iphone_15_128gb',
    familyRef: 'fam_apple_iphone',
    categoryRef: 'smartphones',
    title: 'Apple iPhone 15 128GB (Black)',
    brand: 'Apple',
    modelNumber: 'A3090',
    identifiers: {
      gtin13: '195949038234',
      mpn: 'MTP03AA/A',
    },
    attributes: {
      storageGb: 128,
      displaySizeInches: 6.1,
      network: '5G',
      estimatedPriceZar: 17499,
    },
    aliases: [
      { phrase: 'iPhone 15 128GB', locale: 'en', source: 'search_query', confidence: 0.99 },
      { phrase: 'Apple iPhone 15', locale: 'en', source: 'search_query', confidence: 0.98 },
      { phrase: 'iphone 15 black', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 8,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG', 'GB', 'US'],
    provenance: {
      sourceRef: 'src_manufacturer_apple',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_deye_8kw_hybrid',
    familyRef: 'fam_deye_inverters',
    categoryRef: 'solar_energy',
    title: 'Deye 8kW Single Phase Hybrid Inverter (SUN-8K-SG01LP1-EU)',
    brand: 'Deye',
    modelNumber: 'SUN-8K-SG01LP1-EU',
    identifiers: {
      gtin13: '6971234567901',
      mpn: 'SUN-8K-SG01LP1-EU',
    },
    attributes: {
      ratedPowerKw: 8.0,
      dcBusVoltage: 48,
      maxPvInputVoltage: 500,
      mpptVoltageRange: '125-425V',
      ipRating: 'IP65',
      warrantyYears: 5,
      estimatedPriceZar: 26999,
    },
    aliases: [
      { phrase: 'Deye 8kVA inverter', locale: 'en', source: 'merchant_usage', confidence: 0.95 },
      { phrase: 'Deye 8kw hybrid', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 18,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE', 'NG'],
    provenance: {
      sourceRef: 'src_manufacturer_deye',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_sunsynk_5kw_hybrid',
    familyRef: 'fam_sunsynk_inverters',
    categoryRef: 'solar_energy',
    title: 'Sunsynk 5.5kW Single Phase Smart Hybrid Inverter',
    brand: 'Sunsynk',
    modelNumber: 'SUN-5.5K-SG01LP1',
    identifiers: {
      gtin13: '6009876543224',
      mpn: 'SUN-5.5K-SG01LP1',
    },
    attributes: {
      ratedPowerKw: 5.5,
      dcBusVoltage: 48,
      maxPvInputVoltage: 500,
      ipRating: 'IP65',
      warrantyYears: 5,
      estimatedPriceZar: 18450,
    },
    aliases: [
      { phrase: 'Sunsynk 5kw inverter', locale: 'en', source: 'search_query', confidence: 0.95 },
    ],
    compatibilityEdgeCount: 15,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE'],
    provenance: {
      sourceRef: 'src_manufacturer_sunsynk',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_freedomwon_home_5_4',
    familyRef: 'fam_freedom_won_batteries',
    categoryRef: 'solar_energy',
    title: 'Freedom Won LiTE Home 5/4 LiFePO4 5.2kWh Lithium Battery',
    brand: 'Freedom Won',
    modelNumber: 'FW-LITE-HOME-5-4',
    identifiers: {
      gtin13: '6001234567883',
      mpn: 'LITE-HOME-5/4',
    },
    attributes: {
      nominalCapacityKwh: 5.2,
      usableCapacityKwh: 4.16,
      nominalVoltage: 52.0,
      maxDischargeCurrentA: 100,
      cycleLife: 6000,
      warrantyYears: 10,
      estimatedPriceZar: 23800,
    },
    aliases: [
      { phrase: 'Freedom Won 5kwh battery', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 14,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE'],
    provenance: {
      sourceRef: 'src_manufacturer_freedomwon',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_hubble_am2_5kwh',
    familyRef: 'fam_hubble_batteries',
    categoryRef: 'solar_energy',
    title: 'Hubble AM-2 5.12kWh 51.2V Lithium-ion Battery',
    brand: 'Hubble Energy',
    modelNumber: 'AM-2-5.12',
    identifiers: {
      gtin13: '6009890123456',
      mpn: 'HUB-AM2-512',
    },
    attributes: {
      nominalCapacityKwh: 5.12,
      nominalVoltage: 51.2,
      cycleLife: 6000,
      warrantyYears: 10,
      estimatedPriceZar: 19950,
    },
    aliases: [
      { phrase: 'Hubble AM2 battery', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 14,
    status: 'active',
    countryScope: ['ZA', 'ZW'],
    provenance: {
      sourceRef: 'src_manufacturer_hubble',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_canadian_solar_650w',
    familyRef: 'fam_canadian_solar_panels',
    categoryRef: 'solar_energy',
    title: 'Canadian Solar 650W HiKu7 Mono PERC Solar Panel',
    brand: 'Canadian Solar',
    modelNumber: 'CS7N-650MS',
    identifiers: {
      gtin13: '6973456789012',
      mpn: 'CS7N-650MS',
    },
    attributes: {
      ratedPowerWatts: 650,
      efficiencyPercent: 20.9,
      warrantyYears: 12,
      estimatedPriceZar: 1895,
    },
    aliases: [
      { phrase: 'Canadian Solar 650w', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 16,
    status: 'active',
    countryScope: ['ZA', 'ZW', 'KE'],
    provenance: {
      sourceRef: 'src_manufacturer_canadiansolar',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_afrisam_cement_50kg',
    familyRef: 'fam_afrisam_cement',
    categoryRef: 'hardware',
    title: 'AfriSam All Purpose Cement 50kg Bag (CEM II 32.5R)',
    brand: 'AfriSam',
    modelNumber: 'AFRISAM-CEM2-50KG',
    identifiers: {
      gtin13: '6001087000021',
      mpn: 'AFR-CEM2-50KG',
    },
    attributes: {
      weightKg: 50,
      strengthClass: '32.5R',
      sabsApproved: true,
      estimatedPriceZar: 96,
    },
    aliases: [
      { phrase: 'AfriSam cement 50kg', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 8,
    status: 'active',
    countryScope: ['ZA', 'ZW'],
    provenance: {
      sourceRef: 'src_manufacturer_afrisam',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_corobrik_red_terracotta',
    familyRef: 'fam_corobrik_facebrick',
    categoryRef: 'hardware',
    title: 'Corobrik Red Terracotta Travertine Face Brick (Pallet of 500)',
    brand: 'Corobrik',
    modelNumber: 'CORO-TERRA-TRAV-500',
    identifiers: {
      mpn: 'CORO-TRAV-500',
    },
    attributes: {
      quantityPerPallet: 500,
      color: 'Red Terracotta',
      finish: 'Travertine',
      estimatedPriceZar: 2850,
    },
    aliases: [
      { phrase: 'Corobrik face brick pallet', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 4,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_corobrik',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_bosch_gws_grinder',
    familyRef: 'fam_bosch_powertools',
    categoryRef: 'hardware',
    title: 'Bosch Professional GWS 750-115 Angle Grinder 115mm 750W',
    brand: 'Bosch Professional',
    modelNumber: 'GWS 750-115',
    identifiers: {
      gtin13: '3165140822602',
      mpn: '0601394000',
    },
    attributes: {
      powerWatts: 750,
      discDiameterMm: 115,
      estimatedPriceZar: 899,
    },
    aliases: [
      { phrase: 'Bosch angle grinder 115mm', locale: 'en', source: 'search_query', confidence: 0.98 },
    ],
    compatibilityEdgeCount: 6,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_bosch',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_redmi_13_128gb',
    familyRef: 'fam_xiaomi_redmi',
    categoryRef: 'smartphones',
    title: 'Xiaomi Redmi 13 128GB Midnight Black (ICASA Approved)',
    brand: 'Xiaomi',
    modelNumber: '2404ARN45A',
    identifiers: {
      gtin13: '6941812776858',
      mpn: 'REDMI-13-128-BLK',
    },
    attributes: {
      storageGb: 128,
      ramGb: 6,
      batteryMah: 5030,
      estimatedPriceZar: 2499,
    },
    aliases: [
      { phrase: 'Redmi 13 128GB', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 8,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_xiaomi',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_apple_iphone_13_128gb',
    familyRef: 'fam_apple_iphone',
    categoryRef: 'smartphones',
    title: 'Apple iPhone 13 128GB Midnight (Official ICASA ZA Stock)',
    brand: 'Apple',
    modelNumber: 'MLPF3AA/A',
    identifiers: {
      gtin13: '194252690022',
      mpn: 'MLPF3AA/A',
    },
    attributes: {
      storageGb: 128,
      network: '5G',
      estimatedPriceZar: 11999,
    },
    aliases: [
      { phrase: 'iPhone 13 128GB', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 8,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_apple',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_polo_vivo_brakes',
    familyRef: 'fam_ferodo_brakes',
    categoryRef: 'automotive',
    title: 'VW Polo Vivo 1.4 / 1.6 Front Brake Discs & Ferodo Ceramic Pads Kit',
    brand: 'Ferodo / ATE',
    modelNumber: 'FER-VIVO-FR-KIT',
    identifiers: {
      mpn: 'FER-FDB1398-KIT',
    },
    attributes: {
      vehicleFitment: 'VW Polo Vivo 1.4 / 1.6 (2010–2024)',
      discDiameterMm: 256,
      estimatedPriceZar: 1150,
    },
    aliases: [
      { phrase: 'Polo Vivo brake pads and discs', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 6,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_ferodo',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_willard_652_battery',
    familyRef: 'fam_willard_batteries',
    categoryRef: 'automotive',
    title: 'Willard 652 12V 60Ah Maintenance-Free Car Starter Battery',
    brand: 'Willard Batteries',
    modelNumber: 'WILLARD-652-MF',
    identifiers: {
      gtin13: '6001234567876',
      mpn: 'WIL-652-MF',
    },
    attributes: {
      voltage: 12,
      capacityAh: 60,
      warrantyYears: 2,
      estimatedPriceZar: 1450,
    },
    aliases: [
      { phrase: 'Willard 652 car battery', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 12,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_willard',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_golden_cloud_flour_10kg',
    familyRef: 'fam_golden_cloud_flour',
    categoryRef: 'fmcg',
    title: 'Golden Cloud Cake Wheat Flour 10kg (Bale of 5 Bags)',
    brand: 'Golden Cloud',
    modelNumber: 'GC-FLOUR-10KG-B5',
    identifiers: {
      gtin13: '6001007001234',
      mpn: 'GC-CAKE-10KG',
    },
    attributes: {
      weightKg: 50,
      unitWeightKg: 10,
      packCount: 5,
      estimatedPriceZar: 485,
    },
    aliases: [
      { phrase: 'Golden Cloud flour 10kg', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 6,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_premier',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
  {
    canonicalId: 'var_white_star_super_maize_10kg',
    familyRef: 'fam_white_star_maize',
    categoryRef: 'fmcg',
    title: 'White Star Super Maize Meal 10kg (Bale of 5 Bags)',
    brand: 'White Star',
    modelNumber: 'WS-MAIZE-10KG-B5',
    identifiers: {
      gtin13: '6001007005678',
      mpn: 'WS-SUPER-10KG',
    },
    attributes: {
      weightKg: 50,
      unitWeightKg: 10,
      packCount: 5,
      estimatedPriceZar: 395,
    },
    aliases: [
      { phrase: 'White Star maize meal 10kg', locale: 'en', source: 'search_query', confidence: 0.99 },
    ],
    compatibilityEdgeCount: 6,
    status: 'active',
    countryScope: ['ZA'],
    provenance: {
      sourceRef: 'src_manufacturer_pioneer',
      rightsClass: 'PUBLIC_RECORD',
      confidence: 0.99,
      fieldOwner: 'SHOPPAGE_CANONICAL',
      validFrom: '2026-01-01T00:00:00Z',
    },
  },
];

import { MITREND_CANONICAL_PRODUCTS, MITREND_OFFERS } from './mitrend_dataset';

// Enrich canonical products with media, guides, reviews, and compliance certifications
export const SA_CANONICAL_PRODUCTS: ProductVariant[] = [
  ...RAW_CANONICAL_PRODUCTS.map((p) => enrichProductVariant(p)),
  ...MITREND_CANONICAL_PRODUCTS,
];

export const SA_FLAGSHIP_MERCHANTS: Merchant[] = [
  {
    id: 'loc_sunpower_crownmines',
    marketId: 'mkt_dragon_city',
    stallIdentifier: 'Building 2, Shop B-18',
    name: 'SunPower Solutions Crown Mines (Dragon City)',
    addressText: 'Dragon City Wholesale Mall, Building 2 Shop B-18, Crown Mines, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118301100',
      telephone: '+27118301100',
      email: 'sales@sunpowersolutions.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_solarbros_sandton',
    marketId: 'mkt_sandton_city',
    stallIdentifier: 'Level 2, Tech Zone T-04',
    name: 'SolarBros Sandton City',
    addressText: 'Sandton City Shopping Centre, 83 Rivonia Rd, Sandhurst, Sandton, 2196',
    contacts: {
      whatsapp: '+27117841000',
      telephone: '+27117841000',
      email: 'sandton@solarbros.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_techhub_oriental',
    marketId: 'mkt_oriental_plaza',
    stallIdentifier: 'Shop N-45 Grand Bazaar',
    name: 'TechHub Cellular & Electronics Oriental Plaza',
    addressText: 'Oriental Plaza, Shop N-45 Grand Bazaar, Lilian Ngoyi St, Fordsburg, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118386752',
      telephone: '+27118386752',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_spaza_bara',
    marketId: 'mkt_soweto_bara',
    stallIdentifier: 'Stall #104 Taxi Rank Lower Deck',
    name: "Mama's Phone & Solar Spaza (Bara)",
    addressText: 'Chris Hani Baragwanath Transport Interchange, Stall #104, Diepkloof, Soweto, 1862',
    contacts: {
      whatsapp: '+27731002030',
      telephone: '+27731002030',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_mitrend_midrand',
    marketId: 'mkt_midrand_commercial',
    stallIdentifier: 'Warehouse ERF710',
    name: 'Mitrend Products (Pty) Ltd',
    addressText: 'ERF710 Old Road, Halfway Gardens, Midrand, 1686, Gauteng',
    contacts: {
      whatsapp: '+27105007670',
      telephone: '+27105007670',
      email: 'sales@mitrend.co.za',
      website: 'https://mitrend.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_rubicon_sandton',
    marketId: 'mkt_sandton_city',
    stallIdentifier: 'Sandton Gateway Concourse, Unit G-02',
    name: 'Rubicon Electrical & Solar Sandton',
    addressText: '5 Sandton Dr, Sandhurst, Sandton, 2196',
    contacts: {
      whatsapp: '+27119079000',
      telephone: '+27119079000',
      email: 'sales@rubiconsa.com',
      website: 'https://rubiconsa.com',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_herholdts_jhb',
    marketId: 'mkt_dragon_city',
    stallIdentifier: 'Crown Mines Distribution Yard, Bay 4',
    name: "Herholdt's Renewable Wholesale Crown Mines",
    addressText: 'Main Reef Rd & Hanover St, Crown Mines, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118370123',
      telephone: '+27118370123',
      email: 'jhb@herholdts.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_builders_sandton',
    marketId: 'mkt_sandton_city',
    stallIdentifier: 'Builders Trade Desk Bay 1',
    name: 'Builders Warehouse Sandton Trade Counter',
    addressText: 'Rivonia Rd & Katherine St, Sandton, 2196',
    contacts: {
      whatsapp: '+27860284533',
      telephone: '+27860284533',
      email: 'trade@builders.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_cashbuild_crownmines',
    marketId: 'mkt_dragon_city',
    stallIdentifier: 'Building Materials Gate 3',
    name: 'Cashbuild Crown Mines Wholesalers',
    addressText: 'Main Reef Rd, Crown Mines, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118302000',
      telephone: '+27118302000',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_pretoria_cement_yard',
    marketId: 'mkt_pretoria_showgrounds',
    stallIdentifier: 'Yard Depot 12',
    name: 'Pretoria West Hardware & Cement Depot',
    addressText: 'Soutter St, Pretoria West, Pretoria, 0183',
    contacts: {
      whatsapp: '+27123861234',
      telephone: '+27123861234',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_mayfair_motor_spares',
    marketId: 'mkt_oriental_plaza',
    stallIdentifier: 'Amalgam Spares Hub Shop 8',
    name: 'Mayfair Motor Spares & Amalgam Counter',
    addressText: 'Church St & Central Rd, Mayfair, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118375500',
      telephone: '+27118375500',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_autozone_boeing',
    marketId: 'mkt_dragon_city',
    stallIdentifier: 'Wholesale Trade Hub 14',
    name: 'AutoZone Commercial Parts Depot',
    addressText: 'Crown Mines Automotive Strip, Main Reef Rd, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27116181122',
      telephone: '+27116181122',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_dragon_fmcg_wholesalers',
    marketId: 'mkt_dragon_city',
    stallIdentifier: 'Building 4, FMCG Wholesale Bay 101',
    name: 'Dragon City FMCG & Bulk Foods Wholesalers',
    addressText: 'Dragon City Wholesale Mall, Crown Mines, Johannesburg, 2092',
    contacts: {
      whatsapp: '+27118309988',
      telephone: '+27118309988',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_century_power_cape',
    marketId: 'mkt_va_waterfront',
    stallIdentifier: 'Century Trade Park Unit 4',
    name: 'Century Power Solutions Cape Town',
    addressText: 'Century Blvd, Century City, Cape Town, 7441',
    contacts: {
      whatsapp: '+27215551200',
      telephone: '+27215551200',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_merrypak_maitland',
    marketId: 'mkt_maitland_precinct',
    stallIdentifier: 'Packaging Warehouse ERF42',
    name: 'Merrypak Commercial Packaging & Catering',
    addressText: '45 Morningside Rd, Ndabeni, Maitland, Cape Town, 7405',
    contacts: {
      whatsapp: '+27215312244',
      telephone: '+27215312244',
      website: 'https://merrypak.co.za',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
  {
    id: 'loc_umhlanga_solar_gateway',
    marketId: 'mkt_gateway_durban',
    stallIdentifier: 'Commercial Concourse Unit 12',
    name: 'Umhlanga Solar & Inverter Hub (Gateway)',
    addressText: 'Gateway Theatre of Shopping, 1 Palm Blvd, Umhlanga, 4319',
    contacts: {
      whatsapp: '+27315661100',
      telephone: '+27315661100',
    },
    verificationState: 'fully_verified',
    country: 'ZA',
  },
];

export const SA_FLAGSHIP_OFFERS: Offer[] = [
  {
    id: 'off_deye_5kw_sunpower',
    variantRef: 'var_deye_5kw_hybrid',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_sunpower_crownmines',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building 2, Shop B-18',
    price: {
      amount: 19850,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_deye_8kw_rubicon',
    variantRef: 'var_deye_8kw_hybrid',
    destinationType: 'retailer_website',
    merchantRef: 'loc_rubicon_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Sandton Gateway Concourse, Unit G-02',
    price: {
      amount: 26999,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_sunsynk_5kw_herholdts',
    variantRef: 'var_sunsynk_5kw_hybrid',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_herholdts_jhb',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Crown Mines Distribution Yard, Bay 4',
    price: {
      amount: 18450,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_freedomwon_5_4_solarbros',
    variantRef: 'var_freedomwon_home_5_4',
    destinationType: 'retailer_website',
    merchantRef: 'loc_solarbros_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Level 2, Tech Zone T-04',
    price: {
      amount: 23800,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_hubble_am2_century',
    variantRef: 'var_hubble_am2_5kwh',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_century_power_cape',
    marketRef: 'mkt_va_waterfront',
    stallRef: 'Century Trade Park Unit 4',
    price: {
      amount: 19950,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_canadian_650w_sunpower',
    variantRef: 'var_canadian_solar_650w',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_sunpower_crownmines',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building 2, Shop B-18',
    price: {
      amount: 1895,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_ppc_cement_builders',
    variantRef: 'var_ppc_surebuild_50kg',
    destinationType: 'retailer_website',
    merchantRef: 'loc_builders_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Builders Trade Desk Bay 1',
    price: {
      amount: 115,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_afrisam_cement_cashbuild',
    variantRef: 'var_afrisam_cement_50kg',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_cashbuild_crownmines',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building Materials Gate 3',
    price: {
      amount: 96,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_corobrik_pretoria',
    variantRef: 'var_corobrik_red_terracotta',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_pretoria_cement_yard',
    marketRef: 'mkt_pretoria_showgrounds',
    stallRef: 'Yard Depot 12',
    price: {
      amount: 2850,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_bosch_grinder_builders',
    variantRef: 'var_bosch_gws_grinder',
    destinationType: 'retailer_website',
    merchantRef: 'loc_builders_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Builders Trade Desk Bay 1',
    price: {
      amount: 899,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_redmi13_techhub',
    variantRef: 'var_redmi_13_128gb',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_techhub_oriental',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Shop N-45 Grand Bazaar',
    price: {
      amount: 2499,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_iphone13_techhub',
    variantRef: 'var_apple_iphone_13_128gb',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_techhub_oriental',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Shop N-45 Grand Bazaar',
    price: {
      amount: 11999,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_polo_brakes_mayfair',
    variantRef: 'var_polo_vivo_brakes',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_mayfair_motor_spares',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Amalgam Spares Hub Shop 8',
    price: {
      amount: 1150,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_willard_battery_autozone',
    variantRef: 'var_willard_652_battery',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_autozone_boeing',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Wholesale Trade Hub 14',
    price: {
      amount: 1450,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_golden_cloud_dragon',
    variantRef: 'var_golden_cloud_flour_10kg',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_dragon_fmcg_wholesalers',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building 4, FMCG Wholesale Bay 101',
    price: {
      amount: 485,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_white_star_dragon',
    variantRef: 'var_white_star_super_maize_10kg',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_dragon_fmcg_wholesalers',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building 4, FMCG Wholesale Bay 101',
    price: {
      amount: 395,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_deye_5kw_solarbros',
    variantRef: 'var_deye_5kw_hybrid',
    destinationType: 'retailer_website',
    merchantRef: 'loc_solarbros_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Level 2, Tech Zone T-04',
    price: {
      amount: 21500,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'price_changed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_samsung_a16_techhub',
    variantRef: 'var_samsung_a16_128gb',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_techhub_oriental',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Shop N-45 Grand Bazaar',
    price: {
      amount: 2799,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_ja_solar_550w_sunpower',
    variantRef: 'var_ja_solar_550w',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_sunpower_crownmines',
    marketRef: 'mkt_dragon_city',
    stallRef: 'Building 2, Shop B-18',
    price: {
      amount: 1850,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_freedom_won_10kwh_solarbros',
    variantRef: 'var_freedom_won_10kwh',
    destinationType: 'retailer_website',
    merchantRef: 'loc_solarbros_sandton',
    marketRef: 'mkt_sandton_city',
    stallRef: 'Level 2, Tech Zone T-04',
    price: {
      amount: 46900,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'retail_72h',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_samsung_s24_techhub',
    variantRef: 'var_samsung_s24_ultra_256gb',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_techhub_oriental',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Shop N-45 Grand Bazaar',
    price: {
      amount: 23999,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  {
    id: 'off_apple_iphone_15_techhub',
    variantRef: 'var_apple_iphone_15_128gb',
    destinationType: 'merchant_whatsapp',
    merchantRef: 'loc_techhub_oriental',
    marketRef: 'mkt_oriental_plaza',
    stallRef: 'Shop N-45 Grand Bazaar',
    price: {
      amount: 17499,
      currency: 'ZAR',
      sourceTimestamp: new Date().toISOString(),
    },
    availabilityState: 'fresh',
    updateType: 'stock_confirmed',
    freshness: {
      slaClass: 'fast_moving_24h',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      lastConfirmedAt: new Date().toISOString(),
    },
  },
  ...MITREND_OFFERS,
];

export const SA_FLAGSHIP_PASSPORTS: Record<string, TrustPassport> = {
  loc_sunpower_crownmines: {
    merchantId: 'loc_sunpower_crownmines',
    merchantName: 'SunPower Solutions (Crown Mines)',
    freshOffersTodayCount: 14,
    medianResponseMinutes: 12,
    complaintCountLast90d: 0,
    score: 94,
    state: 'VERIFIED_ACTIVE',
  },
  loc_solarbros_sandton: {
    merchantId: 'loc_solarbros_sandton',
    merchantName: 'SolarBros Sandton City',
    freshOffersTodayCount: 28,
    medianResponseMinutes: 8,
    complaintCountLast90d: 0,
    score: 96,
    state: 'VERIFIED_ACTIVE',
  },
  loc_mitrend_midrand: {
    merchantId: 'loc_mitrend_midrand',
    merchantName: 'Mitrend Products (Pty) Ltd',
    freshOffersTodayCount: 157,
    medianResponseMinutes: 5,
    complaintCountLast90d: 0,
    score: 98,
    state: 'VERIFIED_ACTIVE',
  },
};
