/**
 * Major South African Retailers Circular & Deal Aggregator Dataset (Guzzle-Style)
 * High-value specials with DIRECT product URLs pointing straight to the retailer's checkout page.
 */

export interface MajorRetailerDeal {
  id: string;
  title: string;
  brand: string;
  merchantName: string;
  retailerWebsite: string;
  retailerDomain: string;
  category: 'solar_energy' | 'electronics' | 'groceries' | 'hardware' | 'health_beauty' | 'appliances';
  categoryLabel: string;
  directProductUrl: string; // Guaranteed direct URL to the retailer's product page!
  dealPriceZar: number;
  oldPriceZar?: number;
  discountPct?: number;
  badge?: string;
  availability: string;
  locationHint: string;
  imageUrl: string;
  validUntil?: string;
}

export const SA_MAJOR_RETAILER_DEALS: MajorRetailerDeal[] = [
  // ── 1. MAKRO SOUTH AFRICA ──────────────────────────────────────────────────
  {
    id: 'deal_makro_ppc_cement',
    title: 'PPC Surebuild 42.5N General Purpose Cement 50kg',
    brand: 'PPC',
    merchantName: 'Makro South Africa',
    retailerWebsite: 'makro.co.za',
    retailerDomain: 'makro.co.za',
    category: 'hardware',
    categoryLabel: 'Building & Hardware',
    directProductUrl: 'https://www.makro.co.za/hardware-auto/building-materials/cement-concrete/ppc-surebuild-cement-50kg-p-000000000000123984_EA',
    dealPriceZar: 115,
    oldPriceZar: 139,
    discountPct: 17,
    badge: '🔥 CIRCULAR SPECIAL',
    availability: 'In Stock · Click & Collect or Bulk Delivery',
    locationHint: '22 Mega-Warehouse Superstores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_makro_samsung_65_tv',
    title: 'Samsung 65" Crystal UHD 4K Smart TV (DU7000)',
    brand: 'Samsung',
    merchantName: 'Makro South Africa',
    retailerWebsite: 'makro.co.za',
    retailerDomain: 'makro.co.za',
    category: 'electronics',
    categoryLabel: 'Smartphones & Tech',
    directProductUrl: 'https://www.makro.co.za/electronics-appliances/televisions/ultra-hd-tvs/samsung-65-crystal-uhd-4k-tv-p-000000000000492810_EA',
    dealPriceZar: 9999,
    oldPriceZar: 13999,
    discountPct: 29,
    badge: '⚡ BIG DROP',
    availability: 'In Stock · Free Store Delivery',
    locationHint: 'Available Online & in All Makro Superstores',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_makro_whitestar_10kg',
    title: 'White Star Super Maize Meal 10kg Bag',
    brand: 'White Star',
    merchantName: 'Makro South Africa',
    retailerWebsite: 'makro.co.za',
    retailerDomain: 'makro.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.makro.co.za/food/pantry-dry-goods/maize-meal-samp/white-star-super-maize-meal-10kg-p-000000000000019284_EA',
    dealPriceZar: 129,
    oldPriceZar: 159,
    discountPct: 19,
    badge: 'BULK SAVER',
    availability: 'In Stock · Bulk Pallet Available',
    locationHint: 'Nationwide Wholesale Trade Counters',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_makro_defy_freezer',
    title: 'Defy 350L Chest Freezer (White) with Solar Hybrid Ready Mode',
    brand: 'Defy',
    merchantName: 'Makro South Africa',
    retailerWebsite: 'makro.co.za',
    retailerDomain: 'makro.co.za',
    category: 'appliances',
    categoryLabel: 'Appliances',
    directProductUrl: 'https://www.makro.co.za/electronics-appliances/large-appliances/freezers/defy-350l-chest-freezer-white-p-000000000000381920_EA',
    dealPriceZar: 5499,
    oldPriceZar: 6999,
    discountPct: 21,
    badge: '🔥 SPECIAL',
    availability: 'In Stock · Heavy Delivery Available',
    locationHint: 'Makro Warehouse Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
  },

  // ── 2. GAME STORES ─────────────────────────────────────────────────────────
  {
    id: 'deal_game_hisense_55_tv',
    title: 'Hisense 55" 4K Smart UHD TV (A6K Series)',
    brand: 'Hisense',
    merchantName: 'Game Stores',
    retailerWebsite: 'game.co.za',
    retailerDomain: 'game.co.za',
    category: 'electronics',
    categoryLabel: 'Smartphones & Tech',
    directProductUrl: 'https://www.game.co.za/electronics-entertainment/tvs/smart-tvs/hisense-55-4k-smart-tv-p-000000000000819284_EA',
    dealPriceZar: 5999,
    oldPriceZar: 7999,
    discountPct: 25,
    badge: '🔥 GUZZLE CIRCULAR',
    availability: 'In Stock · Click & Collect or Delivery',
    locationHint: '110+ Game Stores in Malls Across South Africa',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_game_russell_hobbs_airfryer',
    title: 'Russell Hobbs 7L Dual-Basket Digital Air Fryer',
    brand: 'Russell Hobbs',
    merchantName: 'Game Stores',
    retailerWebsite: 'game.co.za',
    retailerDomain: 'game.co.za',
    category: 'appliances',
    categoryLabel: 'Appliances',
    directProductUrl: 'https://www.game.co.za/appliances/small-appliances/air-fryers/russell-hobbs-7l-digital-air-fryer-p-000000000000671920_EA',
    dealPriceZar: 1799,
    oldPriceZar: 2499,
    discountPct: 28,
    badge: '⚡ PRICE DROP',
    availability: 'In Stock (Same-Day Collection)',
    locationHint: 'Game Malls Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_game_ryobi_pressure_washer',
    title: 'Ryobi 1200W High Pressure Cleaner Washer 100-Bar',
    brand: 'Ryobi',
    merchantName: 'Game Stores',
    retailerWebsite: 'game.co.za',
    retailerDomain: 'game.co.za',
    category: 'hardware',
    categoryLabel: 'Building & Hardware',
    directProductUrl: 'https://www.game.co.za/diy-auto/outdoor-power/pressure-washers/ryobi-1200w-pressure-washer-p-000000000000428190_EA',
    dealPriceZar: 899,
    oldPriceZar: 1299,
    discountPct: 31,
    badge: '🔥 SPECIAL',
    availability: 'In Stock · Nationwide Delivery',
    locationHint: 'Game Stores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
  },

  // ── 3. BUILDERS WAREHOUSE ──────────────────────────────────────────────────
  {
    id: 'deal_builders_bosch_drill',
    title: 'Bosch Professional GSB 18V-50 Cordless Brushless Impact Combi Drill',
    brand: 'Bosch',
    merchantName: 'Builders Warehouse',
    retailerWebsite: 'builders.co.za',
    retailerDomain: 'builders.co.za',
    category: 'hardware',
    categoryLabel: 'Building & Hardware',
    directProductUrl: 'https://www.builders.co.za/Tools/Power-Tools/Drills-and-Drivers/Bosch-GSB-18V-50-Cordless-Impact-Drill/p/000000000000691240',
    dealPriceZar: 1999,
    oldPriceZar: 2799,
    discountPct: 29,
    badge: '🔥 CONTRACTOR SPECIAL',
    availability: 'In Stock · 2-Hour Click & Collect',
    locationHint: '100+ Builders Warehouse & Express Stores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_builders_deye_inverter',
    title: 'Deye 5kW 48V Single Phase Hybrid Inverter (SUN-5K-SG03LP1-EU)',
    brand: 'Deye',
    merchantName: 'Builders Warehouse',
    retailerWebsite: 'builders.co.za',
    retailerDomain: 'builders.co.za',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://www.builders.co.za/Solar-Power-and-Generators/Inverters/Deye-5kW-Hybrid-Inverter-48V/p/000000000000784291',
    dealPriceZar: 18499,
    oldPriceZar: 21999,
    discountPct: 16,
    badge: '⚡ POWER BACKUP',
    availability: 'In Stock · Free Delivery on Solar Kits',
    locationHint: 'Builders Superstores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df57046475a?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_builders_jojo_tank',
    title: 'JoJo 2500L Vertical Water Storage Tank (Bush Green)',
    brand: 'JoJo Tanks',
    merchantName: 'Builders Warehouse',
    retailerWebsite: 'builders.co.za',
    retailerDomain: 'builders.co.za',
    category: 'hardware',
    categoryLabel: 'Building & Hardware',
    directProductUrl: 'https://www.builders.co.za/Plumbing/Water-Tanks-and-Pumps/Water-Tanks/JoJo-2500L-Vertical-Water-Storage-Tank-Green/p/000000000000219482',
    dealPriceZar: 2899,
    oldPriceZar: 3499,
    discountPct: 17,
    badge: 'BULK SAVER',
    availability: 'In Stock · Yard Collection or Flatbed Delivery',
    locationHint: 'Builders Warehouse Distribution Yards',
    imageUrl: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80',
  },

  // ── 4. CHECKERS / SIXTY60 ──────────────────────────────────────────────────
  {
    id: 'deal_checkers_jacobs_coffee',
    title: 'Jacobs Krönung Freeze-Dried Instant Coffee 200g Jar',
    brand: 'Jacobs',
    merchantName: 'Checkers Sixty60',
    retailerWebsite: 'checkers.co.za',
    retailerDomain: 'checkers.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.checkers.co.za/All-Departments/Food/Hot-Beverages/Coffee/Instant-Coffee/Jacobs-Kronung-Instant-Coffee-200g/p/10128912001_EA',
    dealPriceZar: 119,
    oldPriceZar: 169,
    discountPct: 30,
    badge: '🔥 XTRA SAVINGS',
    availability: 'In Stock · 60-Minute Delivery via Sixty60',
    locationHint: '300+ Checkers Stores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_checkers_sunfoil_oil',
    title: 'Sunfoil Pure Sunflower Cooking Oil 2-Litre Bottle',
    brand: 'Sunfoil',
    merchantName: 'Checkers Sixty60',
    retailerWebsite: 'checkers.co.za',
    retailerDomain: 'checkers.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.checkers.co.za/All-Departments/Food/Food-Cupboard/Cooking-Ingredients/Oil/Sunfoil-Pure-Sunflower-Cooking-Oil-2L/p/10124819001_EA',
    dealPriceZar: 69.99,
    oldPriceZar: 89.99,
    discountPct: 22,
    badge: '🔥 WEEKLY SPECIAL',
    availability: 'In Stock · Sixty60 On Demand',
    locationHint: 'Nationwide Checkers Footprint',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_checkers_babysoft_tp',
    title: 'Baby Soft 2-Ply White Toilet Paper 18-Pack',
    brand: 'Baby Soft',
    merchantName: 'Checkers Sixty60',
    retailerWebsite: 'checkers.co.za',
    retailerDomain: 'checkers.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.checkers.co.za/All-Departments/Household/Paper-and-Tissues/Toilet-Paper/Baby-Soft-2-Ply-Toilet-Paper-White-18-Pack/p/10134918001_EA',
    dealPriceZar: 119.99,
    oldPriceZar: 159.99,
    discountPct: 25,
    badge: 'XTRA SAVINGS',
    availability: 'In Stock · Fast Dispatch',
    locationHint: 'Checkers Supermarkets Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=800&auto=format&fit=crop&q=80',
  },

  // ── 5. PICK N PAY ──────────────────────────────────────────────────────────
  {
    id: 'deal_pnp_weetbix',
    title: 'Bokomo Weet-Bix Wholegrain Wheat Cereal 900g',
    brand: 'Bokomo',
    merchantName: 'Pick n Pay',
    retailerWebsite: 'pnp.co.za',
    retailerDomain: 'pnp.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.pnp.co.za/pnpstorefront/pnp/en/Food-Cupboard/Breakfast-Cereals-%26-Bars/Biscuits-%26-Wheat-Cereal/Bokomo-Weet-Bix-900g/p/000000000000014280_EA',
    dealPriceZar: 49.99,
    oldPriceZar: 64.99,
    discountPct: 23,
    badge: '🔥 SMART SHOPPER',
    availability: 'In Stock · Same-Day Delivery via asap!',
    locationHint: '500+ Pick n Pay Supermarkets Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_pnp_rama_margarine',
    title: 'Rama Original 70% Fat Spread Brick 1kg',
    brand: 'Rama',
    merchantName: 'Pick n Pay',
    retailerWebsite: 'pnp.co.za',
    retailerDomain: 'pnp.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.pnp.co.za/pnpstorefront/pnp/en/Fresh-Food/Dairy-Eggs-%26-Chilled/Butter-%26-Margarine/Margarine-%26-Spreads/Rama-Original-70-Fat-Spread-Brick-1kg/p/000000000000081920_EA',
    dealPriceZar: 44.99,
    oldPriceZar: 59.99,
    discountPct: 25,
    badge: 'SMART SHOPPER',
    availability: 'In Stock · asap! Delivery',
    locationHint: 'Pick n Pay Hypermarkets & Supermarkets',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800&auto=format&fit=crop&q=80',
  },

  // ── 6. WOOLWORTHS SOUTH AFRICA ─────────────────────────────────────────────
  {
    id: 'deal_woolworths_eggs',
    title: 'Woolworths 18 Extra Large Free Range Eggs',
    brand: 'Woolworths',
    merchantName: 'Woolworths South Africa',
    retailerWebsite: 'woolworths.co.za',
    retailerDomain: 'woolworths.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.woolworths.co.za/prod/Food/Eggs-Dairy/Eggs/Free-Range-Eggs/18-Extra-Large-Free-Range-Eggs/_/A-6001009001425',
    dealPriceZar: 79.99,
    oldPriceZar: 94.99,
    discountPct: 16,
    badge: 'QUALITY REWARD',
    availability: 'In Stock · Woolies Dash 60-Min Delivery',
    locationHint: '400+ Woolworths Food Stores Across South Africa',
    imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_woolworths_milk',
    title: 'Woolworths Full Cream Fresh Milk 2-Litre',
    brand: 'Woolworths',
    merchantName: 'Woolworths South Africa',
    retailerWebsite: 'woolworths.co.za',
    retailerDomain: 'woolworths.co.za',
    category: 'groceries',
    categoryLabel: 'Wholesale FMCG',
    directProductUrl: 'https://www.woolworths.co.za/prod/Food/Eggs-Dairy/Milk-Cream/Fresh-Milk/Full-Cream-Fresh-Milk-2L/_/A-6001009001180',
    dealPriceZar: 34.99,
    oldPriceZar: 42.99,
    discountPct: 19,
    badge: 'DAILY FRESH',
    availability: 'In Stock · Woolies Dash Delivery',
    locationHint: 'Woolworths Supermarkets Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80',
  },

  // ── 7. TAKEALOT.COM ────────────────────────────────────────────────────────
  {
    id: 'deal_takealot_sunsynk_8kw',
    title: 'Sunsynk 8kW 48V Single Phase Hybrid Solar Inverter',
    brand: 'Sunsynk',
    merchantName: 'Takealot.com',
    retailerWebsite: 'takealot.com',
    retailerDomain: 'takealot.com',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://www.takealot.com/sunsynk-8kw-hybrid-inverter-48v-single-phase/PLID90823140',
    dealPriceZar: 29999,
    oldPriceZar: 34999,
    discountPct: 14,
    badge: '🔥 DAILY DEAL',
    availability: 'In Stock · Free Nationwide Courier Delivery',
    locationHint: 'Takealot Logistics Distribution Centres',
    imageUrl: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_takealot_dyness_battery',
    title: 'Dyness BX51100 5.12kWh 48V Lithium-ion Solar Battery',
    brand: 'Dyness',
    merchantName: 'Takealot.com',
    retailerWebsite: 'takealot.com',
    retailerDomain: 'takealot.com',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://www.takealot.com/dyness-5-12kwh-bx51100-lithium-battery-48v/PLID92147850',
    dealPriceZar: 17499,
    oldPriceZar: 21999,
    discountPct: 20,
    badge: '⚡ PRICE DROP',
    availability: 'In Stock · Next-Day Dispatch',
    locationHint: 'National Distribution Centres',
    imageUrl: 'https://images.unsplash.com/photo-1558441719-8cf44b4754a6?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_takealot_samsung_s24',
    title: 'Samsung Galaxy S24 Ultra 256GB 5G (Titanium Black)',
    brand: 'Samsung',
    merchantName: 'Takealot.com',
    retailerWebsite: 'takealot.com',
    retailerDomain: 'takealot.com',
    category: 'electronics',
    categoryLabel: 'Smartphones & Tech',
    directProductUrl: 'https://www.takealot.com/samsung-galaxy-s24-ultra-256gb-5g-titanium-black/PLID94829104',
    dealPriceZar: 21999,
    oldPriceZar: 27999,
    discountPct: 21,
    badge: '🔥 FLASH SALE',
    availability: 'In Stock · Same-Day Delivery in JHB & CPT',
    locationHint: 'Takealot Direct Hub',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
  },

  // ── 8. INCREDIBLE CONNECTION ───────────────────────────────────────────────
  {
    id: 'deal_incredible_samsung_a16',
    title: 'Samsung Galaxy A16 128GB LTE Dual SIM (Black)',
    brand: 'Samsung',
    merchantName: 'Incredible Connection',
    retailerWebsite: 'incredible.co.za',
    retailerDomain: 'incredible.co.za',
    category: 'electronics',
    categoryLabel: 'Smartphones & Tech',
    directProductUrl: 'https://www.incredible.co.za/samsung-galaxy-a16-128gb-lte-black-10304918',
    dealPriceZar: 2899,
    oldPriceZar: 3499,
    discountPct: 17,
    badge: '🔥 TECH DROP',
    availability: 'In Stock · Store Collection or Courier',
    locationHint: '70+ Tech Stores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_incredible_ecoflow_river',
    title: 'EcoFlow RIVER 2 Max 512Wh Portable Power Station (500W AC Output)',
    brand: 'EcoFlow',
    merchantName: 'Incredible Connection',
    retailerWebsite: 'incredible.co.za',
    retailerDomain: 'incredible.co.za',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://www.incredible.co.za/ecoflow-river-2-max-512wh-portable-power-station-10319284',
    dealPriceZar: 7999,
    oldPriceZar: 9999,
    discountPct: 20,
    badge: '⚡ LOAD SHEDDING',
    availability: 'In Stock · Immediate Collection',
    locationHint: 'Incredible Hubs Across SA',
    imageUrl: 'https://images.unsplash.com/photo-1592833159155-c62df1b65634?w=800&auto=format&fit=crop&q=80',
  },

  // ── 9. CLICKS GROUP ────────────────────────────────────────────────────────
  {
    id: 'deal_clicks_med_lemon',
    title: 'Med-Lemon Hot Medication Lemon Menthol with Vitamin C 8 Sachets',
    brand: 'Med-Lemon',
    merchantName: 'Clicks Group',
    retailerWebsite: 'clicks.co.za',
    retailerDomain: 'clicks.co.za',
    category: 'health_beauty',
    categoryLabel: 'Health & Beauty',
    directProductUrl: 'https://clicks.co.za/med-lemon_hot-medication-lemon-menthol-with-vitamin-c-8-sachets/p/505',
    dealPriceZar: 54.99,
    oldPriceZar: 69.99,
    discountPct: 21,
    badge: '🔥 CLUB CARD',
    availability: 'In Stock · 850+ Pharmacies Nationwide',
    locationHint: 'All Major Regional Malls & High Streets',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_clicks_nivea_lotion',
    title: 'Nivea Rich Nourishing Body Lotion 400ml Pump',
    brand: 'Nivea',
    merchantName: 'Clicks Group',
    retailerWebsite: 'clicks.co.za',
    retailerDomain: 'clicks.co.za',
    category: 'health_beauty',
    categoryLabel: 'Health & Beauty',
    directProductUrl: 'https://clicks.co.za/nivea_rich-nourishing-body-lotion-400ml/p/118290',
    dealPriceZar: 79.99,
    oldPriceZar: 109.99,
    discountPct: 27,
    badge: '3 FOR 2 DEAL',
    availability: 'In Stock · Same-Day Click & Collect',
    locationHint: 'Clicks Stores Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
  },

  // ── 10. DIS-CHEM PHARMACIES ────────────────────────────────────────────────
  {
    id: 'deal_dischem_panado',
    title: 'Panado 500mg Paracetamol Tablets 24-Pack',
    brand: 'Panado',
    merchantName: 'Dis-Chem Pharmacies',
    retailerWebsite: 'dischem.co.za',
    retailerDomain: 'dischem.co.za',
    category: 'health_beauty',
    categoryLabel: 'Health & Beauty',
    directProductUrl: 'https://www.dischem.co.za/panado-paracetamol-500mg-24-tablets',
    dealPriceZar: 28.95,
    oldPriceZar: 36.95,
    discountPct: 22,
    badge: '🔥 ESSENTIAL SAVING',
    availability: 'In Stock · Dis-Chem DeliverD 60-Min',
    locationHint: '250+ Retail Pharmacies Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_dischem_biogen_whey',
    title: 'Biogen Iso-Whey 100% Premium Protein Powder 908g (Vanilla)',
    brand: 'Biogen',
    merchantName: 'Dis-Chem Pharmacies',
    retailerWebsite: 'dischem.co.za',
    retailerDomain: 'dischem.co.za',
    category: 'health_beauty',
    categoryLabel: 'Health & Beauty',
    directProductUrl: 'https://www.dischem.co.za/biogen-iso-whey-protein-908g-vanilla',
    dealPriceZar: 449,
    oldPriceZar: 579,
    discountPct: 22,
    badge: '⚡ BENEFIT REWARD',
    availability: 'In Stock · Online or In-Store',
    locationHint: 'Dis-Chem Health & Wellness Stores',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&auto=format&fit=crop&q=80',
  },

  // ── 11. LEROY MERLIN SOUTH AFRICA ──────────────────────────────────────────
  {
    id: 'deal_leroy_deye_inverter',
    title: 'Deye Hybrid Inverter 5kW 48V Single Phase (NRS 097 Approved)',
    brand: 'Deye',
    merchantName: 'Leroy Merlin South Africa',
    retailerWebsite: 'leroymerlin.co.za',
    retailerDomain: 'leroymerlin.co.za',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://leroymerlin.co.za/deye-hybrid-inverter-5kw-48v-single-phase-81472910',
    dealPriceZar: 18199,
    oldPriceZar: 21499,
    discountPct: 15,
    badge: '🔥 GRID CERTIFIED',
    availability: 'In Stock · 2-Hour Collection',
    locationHint: 'Greenstone, Fourways, Boksburg, Little Falls Superstores',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df57046475a?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_leroy_dexter_tools',
    title: 'Dexter 130-Piece Homeowner & DIY Mechanics Hand Tool Set in Case',
    brand: 'Dexter',
    merchantName: 'Leroy Merlin South Africa',
    retailerWebsite: 'leroymerlin.co.za',
    retailerDomain: 'leroymerlin.co.za',
    category: 'hardware',
    categoryLabel: 'Building & Hardware',
    directProductUrl: 'https://leroymerlin.co.za/dexter-tool-set-in-toolbox-130-pieces-81451920',
    dealPriceZar: 1199,
    oldPriceZar: 1699,
    discountPct: 29,
    badge: '🔥 DIY PROMO',
    availability: 'In Stock · Superstore Pickup',
    locationHint: 'Leroy Merlin Gauteng Warehouses',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
  },

  // ── 12. SOLARADVICE & INVERTER WAREHOUSE ────────────────────────────────────
  {
    id: 'deal_solaradvice_deye',
    title: 'Deye 5kW 48V Single Phase Hybrid Solar Inverter (SUN-5K-SG03LP1-EU)',
    brand: 'Deye',
    merchantName: 'SolarAdvice South Africa',
    retailerWebsite: 'solaradvice.co.za',
    retailerDomain: 'solaradvice.co.za',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://solaradvice.co.za/shop/solar-power/inverters/hybrid-inverters/deye-5kw-hybrid-inverter/',
    dealPriceZar: 17499,
    oldPriceZar: 20999,
    discountPct: 17,
    badge: '⚡ SOLAR PRICE MATCH',
    availability: 'In Stock · Same-Day Dispatch',
    locationHint: 'Johannesburg Warehouse & Courier Nationwide',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df57046475a?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'deal_inverterwh_victron',
    title: 'Victron MultiPlus-II 48/5000/70-50 230V Inverter Charger',
    brand: 'Victron Energy',
    merchantName: 'Inverter Warehouse South Africa',
    retailerWebsite: 'inverterwarehouse.co.za',
    retailerDomain: 'inverterwarehouse.co.za',
    category: 'solar_energy',
    categoryLabel: 'Solar & Power',
    directProductUrl: 'https://inverterwarehouse.co.za/product/victron-multiplus-ii-48-5000-70-50/',
    dealPriceZar: 23999,
    oldPriceZar: 28499,
    discountPct: 16,
    badge: '🔥 TIER 1 BLUE POWER',
    availability: 'In Stock · 5-Year European Warranty',
    locationHint: 'National Solar Dispatch Centre',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df57046475a?w=800&auto=format&fit=crop&q=80',
  },
];
