# Generated by Django 5.1.15 on 2026-08-25 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('official_registry', 'Official Public Registry (CIPC/SARS/CIDB)'), ('direct_merchant', 'Direct Merchant Confirmation (OTP/Auth)'), ('field_cadastre', 'Field Auditor Physical Visit (GPS/Photo)'), ('manufacturer_doc', 'Manufacturer Datasheet / Engineering Spec'), ('retailer_web_feed', 'Authorized Retailer Feed'), ('public_web_sweep', 'Public Web Sweep (Open Data)')], db_index=True, default='public_web_sweep', max_length=40)),
                ('source_identifier', models.CharField(help_text='URL, document reference, or CIPC enterprise number', max_length=255)),
                ('artifact_hash', models.CharField(db_index=True, help_text='SHA-256 payload checksum', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rights_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='rights.rightssource')),
            ],
            options={
                'verbose_name': 'Evidence Artifact',
                'verbose_name_plural': 'Evidence Artifacts',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claim_type', models.CharField(choices=[('price', 'Price Observation'), ('stock_availability', 'Stock Availability'), ('technical_spec', 'Technical Specification'), ('warranty_terms', 'Warranty Terms'), ('compatibility', 'Device / Battery Compatibility'), ('spatial_location', 'Stall / Mall Physical Location'), ('merchant_identity', 'Merchant Statutory Identity'), ('standards_compliance', 'SABS / NRS 097 Compliance')], db_index=True, max_length=40)),
                ('subject_entity_type', models.CharField(help_text='e.g. MasterProduct, Offer, Merchant, Market', max_length=50)),
                ('subject_entity_id', models.CharField(db_index=True, max_length=120)),
                ('claim_key', models.CharField(help_text='e.g. priceZar, nrs097Certified, stallNumber', max_length=100)),
                ('claim_value', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('candidate', 'Candidate (AI Generated / Pending Evidence)'), ('verified', 'Verified (Evidence Backed)'), ('disputed', 'Disputed'), ('expired', 'Expired / Stale'), ('rejected', 'Rejected (False / Prohibited)')], db_index=True, default='candidate', max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.85, max_digits=5)),
                ('verified_by', models.CharField(blank=True, help_text='Field Auditor, System Rule, or Merchant ID', max_length=150, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('primary_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='evidence.evidenceartifact')),
            ],
            options={
                'verbose_name': 'Evidence Claim',
                'verbose_name_plural': 'Evidence Claims',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observed_value', models.JSONField(default=dict)),
                ('observer_identity', models.CharField(default='system_ingestion_pipeline', max_length=150)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='evidence.evidenceartifact')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='evidence.evidenceclaim')),
            ],
            options={
                'verbose_name': 'Evidence Observation',
                'verbose_name_plural': 'Evidence Observations',
                'ordering': ['-observed_at'],
            },
        ),
    ]
