# Generated by Django 5.1.15 on 2026-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('position', models.IntegerField(default=0, help_text='1-based rank the product held when clicked')),
                ('source', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id', '-created_at'], name='sclk_product_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('result_count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('assistant', 'Assistant')], default='web', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized', '-created_at'], name='sql_norm_created_idx')],
            },
        ),
    ]
