# Generated by Django 5.1.15 on 2026-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='views',
            field=models.IntegerField(db_index=True, default=5000),
        ),
    ]
