# Generated by Django 5.1.15 on 2026-08-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0003_alter_short_likes_alter_short_shares_and_more'),
        ('referrals', '0003_affiliate_referralevent_commission_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shorts', to='referrals.affiliate'),
        ),
    ]
