# Generated by Django 5.1.15 on 2026-08-25 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_id', models.CharField(db_index=True, help_text='e.g. var_deye_5kw_hybrid', max_length=120, unique=True)),
                ('family_ref', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('category_ref', models.CharField(db_index=True, help_text='e.g. solar_energy, smartphones, hardware', max_length=100)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=150, null=True)),
                ('gtin13', models.CharField(blank=True, db_index=True, help_text='GS1 EAN-13 Checksum Barcode', max_length=14, null=True)),
                ('gtin14', models.CharField(blank=True, max_length=15, null=True)),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer Part Number', max_length=100, null=True)),
                ('asin', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft Variant'), ('active', 'Active in Master Catalogue'), ('reference_only', 'Reference Only (No Local Stock Claim)')], db_index=True, default='active', max_length=30)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Structured technical specifications')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of {phrase, locale, confidence}')),
                ('compliance', models.JSONField(blank=True, default=dict, help_text='SABS, NRS 097-2-1, ICASA, warrantyYears')),
                ('reviews_summary', models.JSONField(blank=True, default=dict, help_text='Rating distribution, pros, cons, buyer reviews')),
                ('guides', models.JSONField(blank=True, default=dict, help_text='Troubleshooting, CoC advice, FAQs')),
                ('media_items', models.JSONField(blank=True, default=dict, help_text='Gallery, videos, PDF datasheets')),
                ('compatibility_edge_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Master Product',
                'verbose_name_plural': 'Master Products',
                'ordering': ['brand', 'title'],
            },
        ),
    ]
