# Generated by Django 5.1.15 on 2026-08-28 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_pattern_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='bullet_points',
            field=models.JSONField(blank=True, default=list, help_text='Key feature bullets'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='condition_type',
            field=models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used'), ('open_box', 'Open Box')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Factual, merchant-neutral description of what the product is'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='gtin12',
            field=models.CharField(blank=True, help_text='GS1 UPC-A / GTIN-12', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='gtin8',
            field=models.CharField(blank=True, help_text='GS1 GTIN-8', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='handle',
            field=models.SlugField(blank=True, help_text='SEO URL handle; falls back to canonical_id', max_length=255),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='search_terms',
            field=models.CharField(blank=True, help_text='Backend search terms, not rendered on page', max_length=255),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Free-form discovery tags'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='unit_dimensions_mm',
            field=models.JSONField(blank=True, default=dict, help_text='{length, width, height} in millimetres'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='unit_weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='asin',
            field=models.CharField(blank=True, help_text='Amazon ASIN', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manufacturer', 'Manufacturer / Brand Asset'), ('merchant', 'Merchant Uploaded'), ('evidence', 'Field Evidence Capture')], default='manufacturer', max_length=20)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
