# Generated by Django 6.1 on 2026-08-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_pattern_indexes'),
        ('merchants', '0005_merchant_operating_hours_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('google_category_id', models.IntegerField(db_index=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True when set by an admin rather than the seed default')),
            ],
            options={
                'verbose_name': 'Category Mapping',
                'verbose_name_plural': 'Category Mappings',
            },
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='google_category_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Override of Google product category id (else resolved from category_ref)', null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Primary product image (served as g:image_link in feeds)', null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='Verified Buyer', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_verified_buyer', models.BooleanField(default=False)),
                ('moderation_state', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='merchants.merchant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('merchant__isnull', True), ('product__isnull', False)), models.Q(('merchant__isnull', False), ('product__isnull', True)), _connector='OR'), name='review_targets_exactly_one')],
            },
        ),
    ]
