# Generated by Django 5.1.15 on 2026-08-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_normalize_product_status_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterproduct',
            options={'ordering': ['id'], 'verbose_name': 'Master Product', 'verbose_name_plural': 'Master Products'},
        ),
    ]
