# Generated by Django 5.1.15 on 2026-08-29 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pg_textsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_id', models.IntegerField(help_text='Google taxonomy node id', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(db_index=True, help_text='e.g. Electronics > Communications > Telephony > Mobile Phones', max_length=1000)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('sector', models.CharField(blank=True, db_index=True, help_text='Coarse vertical (category_ref) this node feeds', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Google Taxonomy Category',
                'verbose_name_plural': 'Google Taxonomy Categories',
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='master_category',
            field=models.ForeignKey(blank=True, help_text='Google product taxonomy leaf', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='CategoryPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='catalog.category')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category Closure Row',
                'verbose_name_plural': 'Category Closure Rows',
                'indexes': [models.Index(fields=['descendant'], name='catpath_descendant_idx')],
                'constraints': [models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uniq_category_path_pair')],
            },
        ),
    ]
