# Generated by Django 5.1.15 on 2026-08-25 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rights_class', models.CharField(choices=[('PUBLIC_RECORD', 'Public Official Record'), ('DIRECT_MERCHANT_AUTHORISED', 'Direct Merchant Authorized'), ('PARTNER_CONTRACTUAL_FEED', 'Partner Contractual API Feed'), ('OPEN_DATA_COMMERCIAL', 'Open Data Commercial License'), ('BLOCKED', 'Blocked / Unverified')], db_index=True, default='BLOCKED', max_length=40)),
                ('status', models.CharField(choices=[('BLOCKED', 'BLOCKED (Default)'), ('CLEARED', 'CLEARED for Publication'), ('SUSPENDED', 'SUSPENDED'), ('TERMINATED', 'TERMINATED')], db_index=True, default='BLOCKED', max_length=30)),
                ('permitted_fields', models.JSONField(blank=True, default=list)),
                ('ai_use_permitted', models.BooleanField(default=False, help_text='Explicit consent for AI model inference and training processing')),
                ('suppression_sla_hours', models.IntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Rights Source',
                'verbose_name_plural': 'Rights Sources',
                'ordering': ['name'],
            },
        ),
    ]
